### ISSUE TITLE
Can't wrap widget list with new widget assist by Alt+Enter

### ISSUE THREAD

**Issue by wisit-phusi** [flutter/flutter-intellij#2448]
Use on OSX system.

## Steps to Reproduce

1. Press Alt+Enter on Android Studio.
2. Nothing appears.

**Comment by pq** [comment]
Hi @wisit-phusi.  Thanks for the report.  

What version of IDEA and the plugin are you using? How recent is your Flutter?  Could you run `flutter doctor` and paste in the output?

**Comment by wisit-phusi** [comment]
I use IntelliJ IDEA 2018.1.4, Android Studio 3.1.3, Flutter Plugin version 25.0.1 and Dart Plugin version 173.4700.

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
[✓] VS Code (version 1.24.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by pq** [comment]
Thanks!

@wisit-phusi : does it work unreliably or never?

Anything in the error log? (**Help > Show Log in Finder**)

/cc @scheglov

**Comment by scheglov** [comment]
Do you have an example when it does not work?
I tried it now manually (and we have tests), and it still works.
![image](https://user-images.githubusercontent.com/384794/42106986-b4392494-7b8a-11e8-8869-5f7a8bd89814.png)

**Comment by wisit-phusi** [comment]
I have tried to do like this, But it still not appeared. I don’t sure that
I have ever disabled it before. Has it way to check that enable or disable?

**Comment by wisit-phusi** [comment]
@scheglov 
This is an example when it does not work.
<img width="875" alt="screen shot 2561-06-30 at 01 06 32" src="https://user-images.githubusercontent.com/32625530/42107617-43cbd5bc-7c02-11e8-98ab-c9271a9c83be.png">

**Comment by scheglov** [comment]
Do you get any Dart Quick Assists (Alt+Enter) from IDE?

**Comment by wisit-phusi** [comment]
Android Studio and Intellij

**Comment by quangson91** [comment]
@wisit-phusi I thought you may disable `Dart Quick Assists (Alt+Enter) from IDE`.
<img width="754" alt="disable" src="https://user-images.githubusercontent.com/6185205/42123479-e9907820-7c7c-11e8-964d-bad51a6814d0.png">

To make sure, please open intellij/androidstudio setting page. In search text book type `assistant`.
Then check in `Editor -> Intentions` -> You should checked `Quick assist powered by the Dart Analysis Server.`.

Here is the screenshot for more detail.

<img width="1031" alt="check" src="https://user-images.githubusercontent.com/6185205/42123486-238a8354-7c7d-11e8-9844-b2c72f33bfe7.png">

**Comment by srinivasPaidisetti** [comment]
thank you very much I had the same issue occurred. So, I followed the above steps u said  Then it works fine

**Comment by francyfre** [comment]
in Android studio, when i close my widgets... there is no name in last brackets (name of the widget close)... i have suggest when i use alt+enter... so i dont know whats problem is!

thankForHelpMe

**Comment by lijie28** [comment]
> @wisit-phusi I thought you may disable `Dart Quick Assists (Alt+Enter) from IDE`.
> <img alt="disable" width="754" src="https://user-images.githubusercontent.com/6185205/42123479-e9907820-7c7c-11e8-964d-bad51a6814d0.png">
> 
> To make sure, please open intellij/androidstudio setting page. In search text book type `assistant`.
> Then check in `Editor -> Intentions` -> You should checked `Quick assist powered by the Dart Analysis Server.`.
> 
> Here is the screenshot for more detail.
> 
> <img alt="check" width="1031" src="https://user-images.githubusercontent.com/6185205/42123486-238a8354-7c7d-11e8-9844-b2c72f33bfe7.png">

thanks,it really helps

**Comment by Kav47** [comment]
It happens when you try to wrap a list of widgets like this:

```
Expanded(
                child: FlatButton(
                  onPressed: (){
                    playSound(5);
                  },
                  color: Colors.teal,
                ),
              ),
              FlatButton(
                onPressed: (){
                  playSound(6);
                },
                color: Colors.blue,
              ),
```

Here I just wrapped my first **FlatButton** widget with **Expanded**, now there is a red color box around my **Expanded** widget. 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/4541988/73303074-a21c6780-420d-11ea-8dff-97379cf9ed31.png">

When I try to wrap my second **FlatButton** widget by Alt+Enter or Option+ Enter (mac)

**Comment by sokkhimk** [comment]
> @wisit-phusi I thought you may disable `Dart Quick Assists (Alt+Enter) from IDE`.
> <img alt="disable" width="754" src="https://user-images.githubusercontent.com/6185205/42123479-e9907820-7c7c-11e8-964d-bad51a6814d0.png">
> 
> To make sure, please open intellij/androidstudio setting page. In search text book type `assistant`.
> Then check in `Editor -> Intentions` -> You should checked `Quick assist powered by the Dart Analysis Server.`.
> 
> Here is the screenshot for more detail.
> 
> <img alt="check" width="1031" src="https://user-images.githubusercontent.com/6185205/42123486-238a8354-7c7d-11e8-9844-b2c72f33bfe7.png">

Thank you for solution. It 's  work for me.

**Comment by lifeanddeath** [comment]
Hi everyone, I followed the aforementioned solution, but unfortunately it still doesn't work for me.
The problem with mine is that if i click on the widget, i get a yellow bulb appearing on the left hand side and i can go over with mouse and click on whatever widget I want. But this is extremely time consuming and annoying after a while, so i wanna do it with alt+ enter combination but then i get only suggestions for java. how am i suppose to fix this? could possibly someone help me for gods sake pls?

<img width="1440" alt="Screenshot 2020-04-25 at 22 04 12" src="https://user-images.githubusercontent.com/6498387/80289756-113c2600-8741-11ea-91d9-7da7273f0221.png">

<img width="1440" alt="Screenshot 2020-04-25 at 22 03 50 1" src="https://user-images.githubusercontent.com/6498387/80289758-15684380-8741-11ea-872d-83edb83567ef.png">

**Comment by Deepanshu-Rohilla** [comment]
Thank you very much...

**Comment by asheshpaul** [comment]
> @wisit-phusi I thought you may disable `Dart Quick Assists (Alt+Enter) from IDE`.
> <img alt="disable" width="754" src="https://user-images.githubusercontent.com/6185205/42123479-e9907820-7c7c-11e8-964d-bad51a6814d0.png">
> 
> To make sure, please open intellij/androidstudio setting page. In search text book type `assistant`.
> Then check in `Editor -> Intentions` -> You should checked `Quick assist powered by the Dart Analysis Server.`.
> 
> Here is the screenshot for more detail.
> 
> <img alt="check" width="1031" src="https://user-images.githubusercontent.com/6185205/42123486-238a8354-7c7d-11e8-9844-b2c72f33bfe7.png">

Thank you very much

**Comment by mochammadfawwaz** [comment]
![image](https://user-images.githubusercontent.com/22051898/92568527-7f752580-f2a9-11ea-8ba2-ec11aaeeba3c.png)

hey bro i have same problem but in my case im use vscode..
can you help me to fix this?
i cant automatically add "refactor -> wrap with column"

thank youu

**Comment by felipecastrosales** [comment]
> @ wisit-phusi achei que você pode desativar `Dart Quick Assists (Alt+Enter) from IDE`.
> <img alt="desabilitar" width="754" src="https://user-images.githubusercontent.com/6185205/42123479-e9907820-7c7c-11e8-964d-bad51a6814d0.png">
> 
> Para ter certeza, abra a página de configuração do intellij / androidstudio. No tipo de livro de texto de pesquisa `assistant`.
> Em seguida, verifique `Editor -> Intentions`-> Você deve verificar `Quick assist powered by the Dart Analysis Server.`.
> 
> Aqui está a imagem para mais detalhes.
> 
> <img alt="Verifica" width="1031" src="https://user-images.githubusercontent.com/6185205/42123486-238a8354-7c7d-11e8-9844-b2c72f33bfe7.png">



> @ wisit-phusi achei que você pode desativar `Dart Quick Assists (Alt+Enter) from IDE`.
> <img alt="desabilitar" width="754" src="https://user-images.githubusercontent.com/6185205/42123479-e9907820-7c7c-11e8-964d-bad51a6814d0.png">
> 
> Para ter certeza, abra a página de configuração do intellij / androidstudio. No tipo de livro de texto de pesquisa `assistant`.
> Em seguida, verifique `Editor -> Intentions`-> Você deve verificar `Quick assist powered by the Dart Analysis Server.`.
> 
> Aqui está a imagem para mais detalhes.
> 
> <img alt="Verifica" width="1031" src="https://user-images.githubusercontent.com/6185205/42123486-238a8354-7c7d-11e8-9844-b2c72f33bfe7.png">

WOW! Thank You!

**Comment by SandaliTharuki** [comment]
I'm having a similar issue. When I press ALT + Enter I get other options without "Wrap with a new widget' which I want to use here. Please can someone help me?

**Comment by babyguy** [comment]
> @ wisit-phusi Pensé que podrías desactivar `Dart Quick Assists (Alt+Enter) from IDE`.
> <img alt="inhabilitar" width="754" src="https://user-images.githubusercontent.com/6185205/42123479-e9907820-7c7c-11e8-964d-bad51a6814d0.png">
> 
> Para asegurarse, abra la página de configuración de intellij / androidstudio. En el tipo de libro de texto de búsqueda `assistant`.
> Luego regístrese `Editor -> Intentions`-> Debería verificarlo `Quick assist powered by the Dart Analysis Server.`.
> 
> Aquí está la captura de pantalla para más detalles.
> 
> <img alt="cheque" width="1031" src="https://user-images.githubusercontent.com/6185205/42123486-238a8354-7c7d-11e8-9844-b2c72f33bfe7.png">

Gracias colega tenia mucho tiempo esa duda :+1:

**Comment by Ahmedelassar** [comment]
From the top navbar click on file -> settings -> intentions then search for ( your desired programming language and then check the option, it should work without restarting android studio

**Comment by Ahmedelassar** [comment]
> I'm having a similar issue. When I press ALT + Enter I get other options without "Wrap with a new widget' which I want to use here. Please can someone help me?

From the top navbar click on file -> settings -> intentions then search for ( your desired programming language and then check the option, it should work without restarting android studio

**Comment by FrenchFries-French** [comment]
Hey guys, seem that I have a similar Problem. I also clicked on Preferences and checked the box "Quick" as mentioned several times but I still only get this, when I press alt + enter:

adjust code style settings

Can someone help me please ?

**Comment by ukreddy-erwin** [comment]
![image](https://user-images.githubusercontent.com/21240709/115959209-bb9f8280-a528-11eb-861c-0ba89875a41f.png)
neither alt+enter also working

**Comment by pilotsis** [comment]
> @wisit-phusi devre dışı bırakabileceğinizi düşündüm `Dart Quick Assists (Alt+Enter) from IDE`. <img alt="devre dışı bırakmak" width="754" src="https://user-images.githubusercontent.com/6185205/42123479-e9907820-7c7c-11e8-964d-bad51a6814d0.png">
> 
> Emin olmak için lütfen intellij/androidstudio ayar sayfasını açın. Arama metin kitabı türünde `assistant`. sonra giriş yap `Editor -> Intentions`-> Kontrol etmelisin `Quick assist powered by the Dart Analysis Server.`.
> 
> İşte daha fazla ayrıntı için ekran görüntüsü.
> 

> <img alt="Kontrol" width="1031" src="https://user-images.githubusercontent.com/6185205/42123486-238a8354-7c7d-11e8-9844-b2c72f33bfe7.png">

Thank you so mach. I've been dealing wtih problem for two days.

**Comment by Amr1440** [comment]
> @wisit-phusi I thought you may disable `Dart Quick Assists (Alt+Enter) from IDE`. <img alt="disable" width="754" src="https://user-images.githubusercontent.com/6185205/42123479-e9907820-7c7c-11e8-964d-bad51a6814d0.png">
> 
> To make sure, please open intellij/androidstudio setting page. In search text book type `assistant`. Then check in `Editor -> Intentions` -> You should checked `Quick assist powered by the Dart Analysis Server.`.
> 
> Here is the screenshot for more detail.
> 
> <img alt="check" width="1031" src="https://user-images.githubusercontent.com/6185205/42123486-238a8354-7c7d-11e8-9844-b2c72f33bfe7.png">

Tried solution but it didnt work coz it was already clicked

**Comment by ZapeeoSheikh** [comment]
I am unable to solve this problem. As the Intentions tab is not shown to my android studio

**Comment by ZapeeoSheikh** [comment]
Oh that's great my problem has been solved now 
let me share my problem and their solution:  I was unable to find my intention in the search of " assistant " 
solution go to file > setting > search [  type "int" and press search  } > intentions > check the box of " dart " 

Done

**Comment by Nguyen-Duc-Hoa** [comment]
> @wisit-phusi I thought you may disable `Dart Quick Assists (Alt+Enter) from IDE`. <img alt="disable" width="754" src="https://user-images.githubusercontent.com/6185205/42123479-e9907820-7c7c-11e8-964d-bad51a6814d0.png">
> 
> To make sure, please open intellij/androidstudio setting page. In search text book type `assistant`. Then check in `Editor -> Intentions` -> You should checked `Quick assist powered by the Dart Analysis Server.`.
> 
> Here is the screenshot for more detail.
> 
> <img alt="check" width="1031" src="https://user-images.githubusercontent.com/6185205/42123486-238a8354-7c7d-11e8-9844-b2c72f33bfe7.png">

thanks, it worked

**Comment by KartikPatadiya** [comment]
@quangson91 Thank You So much

**Comment by Qikcasual** [comment]
@Nguyen-Duc-Hoa bro very very thanks full to you!! because, i am new on Android development!!  i am struggled on this so many days!!! now problem solved!!!

**Comment by almasud** [comment]
> Android Studio on OSX can not use Assists flutter/flutter#18895

I have the same issue and checked the ```Quick assist powered by the Dart Analysis Server``` is already enabled but still faced the issue!!

**Comment by almasud** [comment]
> @wisit-phusi I thought you may disable `Dart Quick Assists (Alt+Enter) from IDE`. <img alt="disable" width="754" src="https://user-images.githubusercontent.com/6185205/42123479-e9907820-7c7c-11e8-964d-bad51a6814d0.png">
> 
> To make sure, please open intellij/androidstudio setting page. In search text book type `assistant`. Then check in `Editor -> Intentions` -> You should checked `Quick assist powered by the Dart Analysis Server.`.
> 
> Here is the screenshot for more detail.
> 
> <img alt="check" width="1031" src="https://user-images.githubusercontent.com/6185205/42123486-238a8354-7c7d-11e8-9844-b2c72f33bfe7.png">

I have the same issue even though the ```Quick assist powered by the Dart Analysis Server``` is already enabled on my Android Studio Giraffe | 2022.3.1 Patch 1 for MacOSX !

**Comment by Zeeshan-H** [comment]
Same problem for me too. Even i am using Android Studio Giraffe and visual studio code too but flutter refactorings not working. For instance i can't wrap a widget.

**Comment by kajalramnani** [comment]
In my case, I uninstalled this plugin and now my alt + enter works fine. 
Plugin :  **Bloc , Clean architecture**
![Screenshot 2024-02-13 at 12 26 25 ### PM](https://github.com/flutter/flutter-intellij/assets/144235811/3168d7e6-04b4-4fbd-91e0-07ed8664625a)

**Comment by tmunier** [comment]
The solution for me was the shortcut "command" + "." (Mac)

**Comment by IanMurnane** [comment]
If you can't see File -> Settings -> Intentions, use the search bar

I had to disable quick assist, apply, click reset, re-enable, apply, ok..   then it started working!

**Comment by travisbikkle** [comment]
In my case, I used [riverpod lint](https://riverpod.dev/docs/introduction/getting_started#enabling-riverpod_lintcustom_lint),
after remove it from analysis_options.yaml, problem solved. Hope it helps.

before:
<img width="797" alt="image" src="https://github.com/user-attachments/assets/2892409e-9c28-48cc-84ec-3221200fd3d2">

<img width="797" alt="image" src="https://github.com/user-attachments/assets/64fba4a2-ce35-44e3-8a9a-d828dfd64a28">

after:

<img width="491" alt="image" src="https://github.com/user-attachments/assets/47041be4-03df-4b3a-a56a-07dab568d115">

**Comment by yashkoladiya5** [comment]
Simply if nothing works then go to Dart Analysis and go to settings and enable Scope Analysis to the current project...This works for me
