### ISSUE TITLE
Widget inspector empty

### ISSUE THREAD

**Issue by xster** [flutter/flutter-intellij#2642]
Ran Flutter Gallery. 

The render object tree shows up but the widget tree view is empty. 

<img width="1742" alt="screen shot 2018-09-28 at 7 46 36 pm" src="https://user-images.githubusercontent.com/156888/46240104-66db0180-c357-11e8-80cf-1bf3a08ef589.png">

**Comment by devoncarew** [comment]
/cc @jacob314 

@xster, can you provide some version information? For IntelliJ, the Flutter plugin, and the flutter framework? Thanks!

**Comment by xster** [comment]
Ah, reproduced it again:

plugin: 29.0.4, 
flutter: v0.9.7-pre.64

Ran the gallery, clicked into something with the widget inspector and came back blank.

**Comment by xster** [comment]
ah, perhaps a slight bit of useful information. If I open flutter/examples/flutter_gallery in intellij, then the widget inspector works. If I open flutter/, then the empty panel issue appears.

**Comment by jacob314** [comment]
This was a bug with --track-widget-creation that has been fixed.

**Comment by wilburt** [comment]
Please, I am experiencing this error with the following setup on Android Studio:
Plugin: v38.1.1
Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G84, locale
    en-GB)

I noticed that this usually happens when I click on the *Refresh Widget Info*

**Comment by BurningAXE** [comment]
I experience the same issue with Android Studio on macOS. Widget Inspector is either empty from the start or becomes empty when I switch between Widgets/Render tree/Performance. This essentially makes view debugging impossible!

**Comment by vkammerer** [comment]
I am also still experiencing this issue. `flutter doctor` returns no error and I am on the latest version of flutter and of the flutter plugin in Android Studio
