### ISSUE TITLE
update the enablement of the restart buttons (was: crash while restarting)

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#332]
Repro steps:
1. Open some Flutter app in IntelliJ
2. Start debugging
3. Once the app has started, click the 'restart' button fast 5-10 times in a row

Result:

This crash:

```
Starting device daemon...
Launching loader on Nexus 5X...
--------- beginning of main
Observatory listening on http://127.0.0.1:8100
Diagnostic server listening on http://127.0.0.1:8101
Synced 8.3MB.
Connected to _flutterView/0xdb11b090.
Running lib/main.dart on Nexus 5X...
Application running.
Error from flutter daemon: Bad state: Future already completed
dart:async                                                        _AsyncCompleter.complete
package:flutter_tools/src/vmservice.dart 921                      FlutterView.runFromSource.<async>.<fn>
===== asynchronous gap ===========================
dart:async                                                        _StreamImpl.listen
package:flutter_tools/src/vmservice.dart 916                      FlutterView.runFromSource.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/vmservice.dart                          FlutterView.runFromSource
package:flutter_tools/src/hot.dart 396                            HotRunner._launchInView.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner._launchInView
package:flutter_tools/src/hot.dart 408                            HotRunner._launchFromDevFS.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner._launchFromDevFS
package:flutter_tools/src/hot.dart 417                            HotRunner._restartFromSources.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/hot.dart 367                            HotRunner._updateDevFS.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 421                          DevFS.update.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 173                          ServiceProtocolDevFSOperations.writeSource.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 559                      VM.invokeRpcRaw.<async>
dart:async                                                        _SyncCompleter.complete
package:json_rpc_2/src/client.dart 175                            Client._handleSingleResponse
package:json_rpc_2/src/client.dart 165                            Client._handleResponse
dart:async                                                        _StreamController.add
package:json_rpc_2/src/peer.dart 92                               Peer.listen.<fn>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                                HotRunner._restartFromSources
package:flutter_tools/src/hot.dart 456                            HotRunner.restart.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner.restart
package:flutter_tools/src/commands/daemon.dart 619                AppInstance.restart
package:flutter_tools/src/commands/daemon.dart 393                AppDomain.restart.<async>.<fn>
package:flutter_tools/src/base/context.dart 75                    AppContext._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/base/context.dart                       AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 634                AppInstance._runInZone
package:flutter_tools/src/commands/daemon.dart 392                AppDomain.restart.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/daemon.dart                    AppDomain.restart
package:flutter_tools/src/commands/daemon.dart 180                Domain.handleCommand.<fn>
dart:async                                                        Future.Future.sync
package:flutter_tools/src/commands/daemon.dart 178                Domain.handleCommand
package:flutter_tools/src/commands/daemon.dart 146                Daemon._handleRequest
package:flutter_tools/src/commands/daemon.dart 100                Daemon.Daemon.<fn>
===== asynchronous gap ===========================
dart:async                                                        _ForwardingStream.listen
package:flutter_tools/src/commands/daemon.dart 99                 Daemon.Daemon
package:flutter_tools/src/commands/daemon.dart 64                 DaemonCommand.runCommand.<fn>
package:flutter_tools/src/base/context.dart 75                    AppContext._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/base/context.dart                       AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 54                 DaemonCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 150         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 187                          Cache.updateAll.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 117         FlutterCommand.run
package:args/command_runner.dart 183                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 136                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 186  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 72                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 105                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 105                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 132  FlutterCommandRunner.run
package:flutter_tools/executable.dart 94                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 88                          main.<async>

Error from flutter daemon: Bad state: Future already completed
dart:async                                                        _AsyncCompleter.complete
package:flutter_tools/src/vmservice.dart 921                      FlutterView.runFromSource.<async>.<fn>
===== asynchronous gap ===========================
dart:async                                                        _StreamImpl.listen
package:flutter_tools/src/vmservice.dart 916                      FlutterView.runFromSource.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/vmservice.dart                          FlutterView.runFromSource
package:flutter_tools/src/hot.dart 396                            HotRunner._launchInView.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner._launchInView
package:flutter_tools/src/hot.dart 408                            HotRunner._launchFromDevFS.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner._launchFromDevFS
package:flutter_tools/src/hot.dart 417                            HotRunner._restartFromSources.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/hot.dart 367                            HotRunner._updateDevFS.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 421                          DevFS.update.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 173                          ServiceProtocolDevFSOperations.writeSource.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 559                      VM.invokeRpcRaw.<async>
dart:async                                                        _SyncCompleter.complete
package:json_rpc_2/src/client.dart 175                            Client._handleSingleResponse
package:json_rpc_2/src/client.dart 165                            Client._handleResponse
dart:async                                                        _StreamController.add
package:json_rpc_2/src/peer.dart 92                               Peer.listen.<fn>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                                HotRunner._restartFromSources
package:flutter_tools/src/hot.dart 456                            HotRunner.restart.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner.restart
package:flutter_tools/src/commands/daemon.dart 619                AppInstance.restart
package:flutter_tools/src/commands/daemon.dart 393                AppDomain.restart.<async>.<fn>
package:flutter_tools/src/base/context.dart 75                    AppContext._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/base/context.dart                       AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 634                AppInstance._runInZone
package:flutter_tools/src/commands/daemon.dart 392                AppDomain.restart.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/daemon.dart                    AppDomain.restart
package:flutter_tools/src/commands/daemon.dart 180                Domain.handleCommand.<fn>
dart:async                                                        Future.Future.sync
package:flutter_tools/src/commands/daemon.dart 178                Domain.handleCommand
package:flutter_tools/src/commands/daemon.dart 146                Daemon._handleRequest
package:flutter_tools/src/commands/daemon.dart 100                Daemon.Daemon.<fn>
===== asynchronous gap ===========================
dart:async                                                        _ForwardingStream.listen
package:flutter_tools/src/commands/daemon.dart 99                 Daemon.Daemon
package:flutter_tools/src/commands/daemon.dart 64                 DaemonCommand.runCommand.<fn>
package:flutter_tools/src/base/context.dart 75                    AppContext._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/base/context.dart                       AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 54                 DaemonCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 150         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 187                          Cache.updateAll.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 117         FlutterCommand.run
package:args/command_runner.dart 183                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 136                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 186  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 72                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 105                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 105                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 132  FlutterCommandRunner.run
package:flutter_tools/executable.dart 94                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 88                          main.<async>

Error: No consumer associated with id: 
Error from flutter daemon: Bad state: Future already completed
dart:async                                                        _AsyncCompleter.complete
package:flutter_tools/src/vmservice.dart 921                      FlutterView.runFromSource.<async>.<fn>
===== asynchronous gap ===========================
dart:async                                                        _StreamImpl.listen
package:flutter_tools/src/vmservice.dart 916                      FlutterView.runFromSource.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/vmservice.dart                          FlutterView.runFromSource
package:flutter_tools/src/hot.dart 396                            HotRunner._launchInView.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner._launchInView
package:flutter_tools/src/hot.dart 408                            HotRunner._launchFromDevFS.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner._launchFromDevFS
package:flutter_tools/src/hot.dart 417                            HotRunner._restartFromSources.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/hot.dart 367                            HotRunner._updateDevFS.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 421                          DevFS.update.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 173                          ServiceProtocolDevFSOperations.writeSource.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 559                      VM.invokeRpcRaw.<async>
dart:async                                                        _SyncCompleter.complete
package:json_rpc_2/src/client.dart 175                            Client._handleSingleResponse
package:json_rpc_2/src/client.dart 165                            Client._handleResponse
dart:async                                                        _StreamController.add
package:json_rpc_2/src/peer.dart 92                               Peer.listen.<fn>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                                HotRunner._restartFromSources
package:flutter_tools/src/hot.dart 456                            HotRunner.restart.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner.restart
package:flutter_tools/src/commands/daemon.dart 619                AppInstance.restart
package:flutter_tools/src/commands/daemon.dart 393                AppDomain.restart.<async>.<fn>
package:flutter_tools/src/base/context.dart 75                    AppContext._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/base/context.dart                       AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 634                AppInstance._runInZone
package:flutter_tools/src/commands/daemon.dart 392                AppDomain.restart.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/daemon.dart                    AppDomain.restart
package:flutter_tools/src/commands/daemon.dart 180                Domain.handleCommand.<fn>
dart:async                                                        Future.Future.sync
package:flutter_tools/src/commands/daemon.dart 178                Domain.handleCommand
package:flutter_tools/src/commands/daemon.dart 146                Daemon._handleRequest
package:flutter_tools/src/commands/daemon.dart 100                Daemon.Daemon.<fn>
===== asynchronous gap ===========================
dart:async                                                        _ForwardingStream.listen
package:flutter_tools/src/commands/daemon.dart 99                 Daemon.Daemon
package:flutter_tools/src/commands/daemon.dart 64                 DaemonCommand.runCommand.<fn>
package:flutter_tools/src/base/context.dart 75                    AppContext._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/base/context.dart                       AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 54                 DaemonCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 150         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 187                          Cache.updateAll.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 117         FlutterCommand.run
package:args/command_runner.dart 183                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 136                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 186  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 72                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 105                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 105                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 132  FlutterCommandRunner.run
package:flutter_tools/executable.dart 94                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 88                          main.<async>

Error from flutter daemon: Bad state: Future already completed
dart:async                                                        _AsyncCompleter.complete
package:flutter_tools/src/vmservice.dart 921                      FlutterView.runFromSource.<async>.<fn>
===== asynchronous gap ===========================
dart:async                                                        _StreamImpl.listen
package:flutter_tools/src/vmservice.dart 916                      FlutterView.runFromSource.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/vmservice.dart                          FlutterView.runFromSource
package:flutter_tools/src/hot.dart 396                            HotRunner._launchInView.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner._launchInView
package:flutter_tools/src/hot.dart 408                            HotRunner._launchFromDevFS.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner._launchFromDevFS
package:flutter_tools/src/hot.dart 417                            HotRunner._restartFromSources.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/hot.dart 367                            HotRunner._updateDevFS.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 421                          DevFS.update.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 173                          ServiceProtocolDevFSOperations.writeSource.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 559                      VM.invokeRpcRaw.<async>
dart:async                                                        _SyncCompleter.complete
package:json_rpc_2/src/client.dart 175                            Client._handleSingleResponse
package:json_rpc_2/src/client.dart 165                            Client._handleResponse
dart:async                                                        _StreamController.add
package:json_rpc_2/src/peer.dart 92                               Peer.listen.<fn>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                                HotRunner._restartFromSources
package:flutter_tools/src/hot.dart 456                            HotRunner.restart.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner.restart
package:flutter_tools/src/commands/daemon.dart 619                AppInstance.restart
package:flutter_tools/src/commands/daemon.dart 393                AppDomain.restart.<async>.<fn>
package:flutter_tools/src/base/context.dart 75                    AppContext._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/base/context.dart                       AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 634                AppInstance._runInZone
package:flutter_tools/src/commands/daemon.dart 392                AppDomain.restart.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/daemon.dart                    AppDomain.restart
package:flutter_tools/src/commands/daemon.dart 180                Domain.handleCommand.<fn>
dart:async                                                        Future.Future.sync
package:flutter_tools/src/commands/daemon.dart 178                Domain.handleCommand
package:flutter_tools/src/commands/daemon.dart 146                Daemon._handleRequest
package:flutter_tools/src/commands/daemon.dart 100                Daemon.Daemon.<fn>
===== asynchronous gap ===========================
dart:async                                                        _ForwardingStream.listen
package:flutter_tools/src/commands/daemon.dart 99                 Daemon.Daemon
package:flutter_tools/src/commands/daemon.dart 64                 DaemonCommand.runCommand.<fn>
package:flutter_tools/src/base/context.dart 75                    AppContext._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/base/context.dart                       AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 54                 DaemonCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 150         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 187                          Cache.updateAll.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 117         FlutterCommand.run
package:args/command_runner.dart 183                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 136                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 186  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 72                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 105                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 105                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 132  FlutterCommandRunner.run
package:flutter_tools/executable.dart 94                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 88                          main.<async>

Error from flutter daemon: Bad state: Future already completed
dart:async                                                        _AsyncCompleter.complete
package:flutter_tools/src/vmservice.dart 921                      FlutterView.runFromSource.<async>.<fn>
===== asynchronous gap ===========================
dart:async                                                        _StreamImpl.listen
package:flutter_tools/src/vmservice.dart 916                      FlutterView.runFromSource.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/vmservice.dart                          FlutterView.runFromSource
package:flutter_tools/src/hot.dart 396                            HotRunner._launchInView.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner._launchInView
package:flutter_tools/src/hot.dart 408                            HotRunner._launchFromDevFS.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner._launchFromDevFS
package:flutter_tools/src/hot.dart 417                            HotRunner._restartFromSources.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/hot.dart 367                            HotRunner._updateDevFS.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 421                          DevFS.update.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 173                          ServiceProtocolDevFSOperations.writeSource.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 559                      VM.invokeRpcRaw.<async>
dart:async                                                        _SyncCompleter.complete
package:json_rpc_2/src/client.dart 175                            Client._handleSingleResponse
package:json_rpc_2/src/client.dart 165                            Client._handleResponse
dart:async                                                        _StreamController.add
package:json_rpc_2/src/peer.dart 92                               Peer.listen.<fn>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                                HotRunner._restartFromSources
package:flutter_tools/src/hot.dart 456                            HotRunner.restart.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner.restart
package:flutter_tools/src/commands/daemon.dart 619                AppInstance.restart
package:flutter_tools/src/commands/daemon.dart 393                AppDomain.restart.<async>.<fn>
package:flutter_tools/src/base/context.dart 75                    AppContext._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/base/context.dart                       AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 634                AppInstance._runInZone
package:flutter_tools/src/commands/daemon.dart 392                AppDomain.restart.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/daemon.dart                    AppDomain.restart
package:flutter_tools/src/commands/daemon.dart 180                Domain.handleCommand.<fn>
dart:async                                                        Future.Future.sync
package:flutter_tools/src/commands/daemon.dart 178                Domain.handleCommand
package:flutter_tools/src/commands/daemon.dart 146                Daemon._handleRequest
package:flutter_tools/src/commands/daemon.dart 100                Daemon.Daemon.<fn>
===== asynchronous gap ===========================
dart:async                                                        _ForwardingStream.listen
package:flutter_tools/src/commands/daemon.dart 99                 Daemon.Daemon
package:flutter_tools/src/commands/daemon.dart 64                 DaemonCommand.runCommand.<fn>
package:flutter_tools/src/base/context.dart 75                    AppContext._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/base/context.dart                       AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 54                 DaemonCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 150         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 187                          Cache.updateAll.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 117         FlutterCommand.run
package:args/command_runner.dart 183                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 136                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 186  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 72                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 105                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 105                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 132  FlutterCommandRunner.run
package:flutter_tools/executable.dart 94                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 88                          main.<async>

Error from flutter daemon: Bad state: Future already completed
dart:async                                                        _AsyncCompleter.complete
package:flutter_tools/src/vmservice.dart 921                      FlutterView.runFromSource.<async>.<fn>
===== asynchronous gap ===========================
dart:async                                                        _StreamImpl.listen
package:flutter_tools/src/vmservice.dart 916                      FlutterView.runFromSource.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/vmservice.dart                          FlutterView.runFromSource
package:flutter_tools/src/hot.dart 396                            HotRunner._launchInView.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner._launchInView
package:flutter_tools/src/hot.dart 408                            HotRunner._launchFromDevFS.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner._launchFromDevFS
package:flutter_tools/src/hot.dart 417                            HotRunner._restartFromSources.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/hot.dart 367                            HotRunner._updateDevFS.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 421                          DevFS.update.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 173                          ServiceProtocolDevFSOperations.writeSource.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 559                      VM.invokeRpcRaw.<async>
dart:async                                                        _SyncCompleter.complete
package:json_rpc_2/src/client.dart 175                            Client._handleSingleResponse
package:json_rpc_2/src/client.dart 165                            Client._handleResponse
dart:async                                                        _StreamController.add
package:json_rpc_2/src/peer.dart 92                               Peer.listen.<fn>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                                HotRunner._restartFromSources
package:flutter_tools/src/hot.dart 456                            HotRunner.restart.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/hot.dart                                HotRunner.restart
package:flutter_tools/src/commands/daemon.dart 619                AppInstance.restart
package:flutter_tools/src/commands/daemon.dart 393                AppDomain.restart.<async>.<fn>
package:flutter_tools/src/base/context.dart 75                    AppContext._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/base/context.dart                       AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 634                AppInstance._runInZone
package:flutter_tools/src/commands/daemon.dart 392                AppDomain.restart.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/daemon.dart                    AppDomain.restart
package:flutter_tools/src/commands/daemon.dart 180                Domain.handleCommand.<fn>
dart:async                                                        Future.Future.sync
package:flutter_tools/src/commands/daemon.dart 178                Domain.handleCommand
package:flutter_tools/src/commands/daemon.dart 146                Daemon._handleRequest
package:flutter_tools/src/commands/daemon.dart 100                Daemon.Daemon.<fn>
===== asynchronous gap ===========================
dart:async                                                        _ForwardingStream.listen
package:flutter_tools/src/commands/daemon.dart 99                 Daemon.Daemon
package:flutter_tools/src/commands/daemon.dart 64                 DaemonCommand.runCommand.<fn>
package:flutter_tools/src/base/context.dart 75                    AppContext._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/base/context.dart                       AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 54                 DaemonCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 150         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 187                          Cache.updateAll.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 117         FlutterCommand.run
package:args/command_runner.dart 183                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 136                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 186  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 72                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 105                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 105                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 132  FlutterCommandRunner.run
package:flutter_tools/executable.dart 94                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 88                          main.<async>
```

**Comment by stevemessick** [comment]
Is this really something that needs to be in the 0.1 milestone?

**Comment by stevemessick** [comment]
Do you mean the `Full Application Restart` button? When I click that one several times I do not see this problem (but I do get another, so it needs work).

**Comment by mit-mit** [comment]
Yes, I mean 'Full application restart'. Sometimes I need to click many times. But sometimes just two clicks with like half a second in between hits this. I seem to hit it more often when using a physical Android device than when using the iOS simulator.

After that the only remedy is to restart IJ, so pretty severe.

**Comment by stevemessick** [comment]
I have code to fix this mostly written but I can't commit it until https://github.com/flutter/flutter/issues/6400 is fixed. See https://github.com/flutter/flutter-intellij/tree/enablement. I still need to tune the code that detects when to enable the buttons, and that depends on getting 6400 fixed.

I did see this sort of crash occur. I was able to recover by stopping the flutter app and restarting it. I did not have to restart IJ.

**Comment by devoncarew** [comment]
Tentatively moving to the current (`0.1.5`) milestone.

**Comment by devoncarew** [comment]
We do have an `app.started` event now, and will soon have better information about when a restart is in progress (well named `app.progress` events).

**Comment by pq** [comment]
FWIW I verified that we still have issues with head:

```
 No consumer associated with id: 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcessZ$2.logError(DartVmServiceDebugProcessZ.java:176)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:411)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:99)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcessZ$2.logError(DartVmServiceDebugProcessZ.java:176)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:411)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:99)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

(Note that this is before any enablement fixes.)
