### ISSUE TITLE
code completion doesn't work in IntelliJ IDEA 2019.1 + Flutter 1.2.1

### ISSUE THREAD

**Issue by MichelMelhem** [flutter/flutter-intellij#3338]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
I recently updated intelij idea ultimate to version 2019.1.
But since then the autocompletion no longer works as you can see in the gif below
<img src="https://media.giphy.com/media/LWpunzR3oeMBxbq1FM/giphy.gif">

## Version info
Flutter version:
 Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale fr-
Flutter plugin version:
34.0.4
Dart plugin version:
191.6138.87

**Comment by Michel-Melhem** [comment]
No one can help me because I'm at a dead end now.

**Comment by ipereto** [comment]
Unfortunately, you are not the only one who has this bug. I have the same problem. The weird thing is when the Class is written, IntelliJ can find the Dart package correctly, but when I try to write it from the start, the code completion doesn't work, IntelliJ says "No suggestions":

![image](https://imgur.com/ZxbpmEY.gif)

Another thing, I don't know why the structure project although the Dart SDK and the flutter plugin are set up, IntelliJ insists to put a different SDK, in my case, JDK, I think the code completion is having problems beacuse of this:

![image](https://i.imgur.com/7HcaVcv.gif)

Meanwhile, I will use Android Studio until this issue is solved.

**Comment by stevemessick** [comment]
@MichelMelhem Sorry, but I cannot see anything in the gif you posted.

@ipereto Are you using the default Darkula theme? If so, you're not getting proper highlighting. There should be a banner at the top of the Scaffold editor, too. It looks like a configuration issue.

Please append the output of `flutter doctor -v`.

Flutter projects do not need a Java JDK. The do need an Android SDK to run on Android devices, and Xcode for iOS.

**Comment by gabrielnemeth** [comment]
Same for me.

Win 10
Intellij Idea 2019.1

![intellij](https://user-images.githubusercontent.com/11211316/55343019-770c9e80-54aa-11e9-958a-e1c1c3afb97d.gif)


```
$ flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale sk-SK)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Gabriel\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.87

[√] VS Code, 64-bit edition (version 1.32.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.25.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by devoncarew** [comment]
Is the Flutter plugin correctly configured in the preferences, `Languages & Frameworks > Flutter` pref page?

**Comment by stevemessick** [comment]
@gabrielnemeth What content is in your Dart Analysis window?

For everyone:
The Dart Analysis window has a toolbar on the left. The top icon should be Restart and the second should be a gear for Settings. Click the gear and choose the bottom option: View analyzer diagnostics. That will open up a web page with lots of info. Are there any exceptions listed? Does the status page show a server process ID and analysis server version number? How many contexts exist? Are there any stats listed under code completion?

**Comment by gabrielnemeth** [comment]
@devoncarew I think so.
![flutter](https://user-images.githubusercontent.com/11211316/55350435-636a3380-54bc-11e9-9753-eca6ddec8ab2.jpg)

@stevemessick here are the analyzer results:
![dart1](https://user-images.githubusercontent.com/11211316/55350466-75e46d00-54bc-11e9-8b80-748399b390af.jpg)
![dart2](https://user-images.githubusercontent.com/11211316/55350467-767d0380-54bc-11e9-9d69-a729a47d759e.jpg)
![FireShot Capture 001 - Analysis Server - localhost](https://user-images.githubusercontent.com/11211316/55350468-767d0380-54bc-11e9-9f00-b1d5ed2e8974.png)

**Comment by stevemessick** [comment]
@bwilkerson @scheglov Do either of you have any idea why code completion would be inoperable here? Does the context (above) look right? I can't imagine why there would be no code completion requests at all.

Would restarting the analysis server help?

**Comment by gabrielnemeth** [comment]
No. I restarted it several times. Also I had this issue on 3 PCs. On 3rd one I did fresh install of the Intellij IDE and flutter as well.

**Comment by MichelMelhem** [comment]
@stevemessick  It doesn't matter if you don't see anything on my gif I have the exactly same problem as @gabrielnemeth

**Comment by bwilkerson** [comment]
> Do either of you have any idea why code completion would be inoperable here?

I don't. Everything above looks right. Could we enable the instrumentation log? I'd like to see whether the problem is that
- IntelliJ isn't sending completion request (unlikely),
- server is responding at all,
- server responds but with an empty list, or
- server throws an exception.

**Comment by stevemessick** [comment]
> Could we enable the instrumentation log?

How is that done?

**Comment by bwilkerson** [comment]
In IntelliJ:
1. select "Find Action..." from the "Help" menu,
2. search for "Registry" and select "Registry...",
3. edit "dart.server.additional.arguments" to include "--instrumentation-log-file=" followed by the path to where you want the file to be written,
4. click "Close",
5. restart the analysis server, and reproduce the invalid behavior (preferably after server has stopped analyzing your code).

**Comment by scheglov** [comment]
I tried on Windows, and it works with Intellij Idea 2019.1, and with updated Flutter.

So, I think that the problem is that Flutter and Dart SDK version is older than expected.
[The first CL](https://github.com/dart-lang/sdk/commit/931051814c8dc68b219170b145daa9a6ac4b8299#diff-967d119cbdc3d0001a75f8b306289b21) for adding new completion support was in
https://github.com/dart-lang/sdk/releases/tag/2.2.0-dev.2.0

**Comment by alexander-doroshko** [comment]
Looking through the IntelliJ log files may also give a clue (Help -> Show Log).

**Comment by MichelMelhem** [comment]
@scheglov i'm alredy running the latest version of flutter as you can see
```
$ flutter upgrade
Upgrading Flutter from C:\src\flutter...
From https://github.com/flutter/flutter
 * [new branch]          Hixie-patch-2   -> origin/Hixie-patch-2
   204eceea9..1bfa2f231  dev             -> origin/dev
   bafe7cbbb..fbefd6b81  master          -> origin/master
 * [new branch]          v1.4.5-hotfixes -> origin/v1.4.5-hotfixes
 * [new branch]          v1.4.6-hotfixes -> origin/v1.4.6-hotfixes
 * [new tag]             v1.4.2          -> v1.4.2
 * [new tag]             v1.4.6-hotfix.1 -> v1.4.6-hotfix.1
 * [new tag]             v1.4.7          -> v1.4.7
 * [new tag]             v1.4.3          -> v1.4.3
 * [new tag]             v1.4.4          -> v1.4.4
 * [new tag]             v1.4.5          -> v1.4.5
 * [new tag]             v1.4.6          -> v1.4.6
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (7 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code (version 1.32.3)
[√] Connected device (1 available)

• No issues found!
```

**Comment by stevemessick** [comment]
@MichelMelhem You'd have to switch to the master channel to see anything.

**Comment by MichelMelhem** [comment]
@stevemessicka

**Comment by devoncarew** [comment]
Bumping to a P0 while to track down why this is happening.

**Comment by lambdabaa** [comment]
I was able to reproduce the issue on the Flutter stable channel but switching to the dev channel with

`flutter channel dev && flutter upgrade`

seems to have fixed the issue for me. Does this fix the issue for folks? The longer explanation is that flutter 1.2.1 has an a version of analysis server which implements a slightly different version of the not-yet-imported completions spec than the Dart IntelliJ plugin client can consume.

**Comment by devoncarew** [comment]
Thanks all for the reports of this issue; we're working on having a fix out as soon as possible.

In the meantime, you can work around the issue by switching to a newer Flutter SDK (either `dev` or `master` will work). As @lambdabaa says above,

```
flutter channel dev && flutter upgrade
```

**Comment by alexander-doroshko** [comment]
Dart plugin with the fix has been released. Try Help -> Check for updates.

**Comment by MichelMelhem** [comment]
Nice!

**Comment by MichelMelhem** [comment]
@alexander-doroshko  I updated the Dart plugin but i always have the same problem

**Comment by stevemessick** [comment]
Thanks!

People need to use the stable channel, right? If you switched to dev you
should switch back to stable after updating the Dart plugin.

**Comment by alexander-doroshko** [comment]
> People need to use the stable channel, right?

Any version of Flutter SDK, any version of Dart SDK, no restrictions.

**Comment by stevemessick** [comment]
This has been resolved. I'm going to leave this issue open for a while, so anyone that hits the issue will easily see the resolution. The resolution is: double-check that everything is up-to-date.

**Comment by lambdabaa** [comment]
> This has been resolved. I'm going to leave this issue open for a while, so anyone that hits the issue will easily see the resolution. The resolution is: double-check that everything is up-to-date.

I have confirmed that upgrading to Dart plugin v191.6183.88 fixes the issue on the Flutter SDK stable channel.

**Comment by rjworks** [comment]
doesn't work for IntelliJ 2020..

**Comment by alexander-doroshko** [comment]
@rjworks  There are no known issues with code completion in the recent versions IntelliJ IDEA, Dart plugin, Flutter plugin, or Flutter SDK. The issue tracked here is definitely fixed long ago.

There might be some misconfiguration in your environment.  We'll be able to help if you file a separate issue with detailed description, including versions of everything, sample project (if possible), screenshots, and steps to reproduce. Please also attach IDE logs (Help -> Collect Logs and Diagnostics Data).

**Comment by ramvdixit** [comment]
The issue is back. Here is my terminal report! Code completion is fully broken and auto suggestions for class imports fail. Also unused variables and objects are not highlighted (greyed-out)

Flutter 2.11.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision b101bfe32f (3 weeks ago) • 2022-02-16 07:36:54 -0800
Engine • revision e355993572
Tools • Dart 2.17.0 (build 2.17.0-69.2.beta) • DevTools 2.10.0-dev.1

**Comment by eggcaker** [comment]
Back in 2023. Code completion is fully broken and auto suggestions for class imports fail. 

Flutter 3.7.0 
Dart 2.19

**Comment by fhensley** [comment]
Yep. Not working for me either. 
Dart Plugin: 223.8214.16
Flutter Plugin: 72.1.4
Flutter (Channel stable, 3.7.4, on macOS 13.2.1 22D68 darwin-arm64, locale en-AU)
Dart SDK version: 2.19.2 (stable) (Tue Feb 7 18:37:17 2023 +0000) on "macos_arm64"
