### ISSUE TITLE
Syntax highlighting not working with new dart files in Android Studio

### ISSUE THREAD

**Issue by CathalButler** [flutter/flutter-intellij#4397]
Hi, 

I recently updated to Android Studio 3.6 running on Linux. After the updated, I started up Android Studio to work on my flutter project and I was asked to update the Dart & Flutter plugins for Android Studio so I did just that. After completing the updates I tried to continue working on my project but now I'm having an issue with new dart files when I make them. 

The syntax highlighting is not working at all with the new dart files as seen in the first photo.![Screenshot_20200226_140236](https://user-images.githubusercontent.com/26792040/75351861-b69d5f80-58a0-11ea-909e-730be56cf92d.png)

In the second one, it seems the syntax highlighting is only working with return types, method types and classes
![Screenshot_20200226_141235](https://user-images.githubusercontent.com/26792040/75352707-1811fe00-58a2-11ea-839b-7e448be00e25.png)

Iv tried disabling the plugins, restart the IDE and then enabling them again with zero luck. I have also disabled my theme plugin in case maybe that is what was causing it but it doesn't seem to be.

Here is my `flutter doctor -v` report

[✓] Flutter (Channel dev, v1.15.3, on Linux, locale en_IE.UTF-8)
    • Flutter version 1.15.3 at /home/cathal/Development/flutter
    • Framework revision 67826bdce5 (2 weeks ago), 2020-02-10 14:59:32 -0800
    • Engine revision 6158f03ef5
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/cathal/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/cathal/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6494.35

[✓] Connected device (1 available)
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

**Comment by VladyslavBondarenko** [comment]
I don't have a linux to check, but on windows flutter syntax works as intended with the last android studio, flutter and dart plugins

**Comment by CathalButler** [comment]
So after some more investigation, it turns out that [Material Theme](https://github.com/ChrisRM/material-theme-jetbrains) is causing the issue.

I am going to close this issue and open it in issues on that repo.

**Comment by CathalButler** [comment]
I'm after testing with Android studio and IntelliJ and both are acting very weird with the Flutter plugin. When I load the IDEs the last classes opened will have syntax highlighting but when I close the class and open it again they don't. It doesn't seem to be the Material Theme plugin as I mentioned before. 

I have tried reinstalling plugins and IDEs to fix the issue and nothing has worked

**Comment by stevemessick** [comment]
I just set up a new linux machine, and everything worked as expected.

Some things to look at:
- analysis server: ensure the Dart analysis server is running, restart it to be sure
- plugins: disable all plugins you installed except Dart and Flutter (remember to restart)
- multiple installations: if you have more than one Flutter installed (I have many) delete all but one
- dev channel: try switching to the stable Flutter channel
- check the IntelliJ log to see if exceptions are being thrown

It could be that something is causing the analysis server to shut down. That would explain having syntax highlighting when you start up but not when opening new files.

**Comment by CathalButler** [comment]
So I did everything you suggested and it seems the problem is with the analysis server. It will start when the IDE opens and syncs the project but it will just randomly stop working after a period of time when I'm working away. It seems to be more buggy with Android Studio. IntelliJ isn't as bad. It's a very weird issue and going off the logs for the IDE they aren't reporting anything serious so I don't know where I should go from here. I can restart it and the server will hang a little and kick in again but sometimes it requires two restarts.

**Comment by stevemessick** [comment]
@CathalButler That's good input, thanks!

@stereotype441 Perhaps you have some debugging tips for this problem?

**Comment by CathalButler** [comment]
Ok, so an update. I checked my logs today right as I opened up IntelliJ and seen that the analysis server had not started up correctly and found this [threadDump.txt](https://github.com/flutter/flutter-intellij/files/4271986/threadDump-20200301-152552.txt)
I'm not really sure what's going on myself so any input would be great, thanks.

**Comment by stevemessick** [comment]
@CathalButler Thanks for following up on this! Looks like it is fixed in the master channel of Flutter. Hopefully it won't take too long to get into stable.

**Comment by CathalButler** [comment]
No worries, kinda a pain having two days downtime debugging it but I updated my kernel and didn't really stop to think that maybe that was the issue till I started having issues with Gradle builds and then I came across that issue post.

**Comment by yvonmanzi** [comment]
@CathalButler Thanks for your suggestions. I realized that after upgrading my Android Studio, Flutter and Dart plugins were disabled waiting to either be upgraded to be kept with their current versions. Making sure they were all enabled once again helped.

**Comment by Solexplorer** [comment]
I faced the same issue, what I've done to overcome it was to copy an existing dart file and rename it. I followed all the suggestion from the guy above tho

**Comment by Bertus-W** [comment]
I still face this issue daily. and sometimes not even new files. highlighting and intelisense are just gone. 

<img width="739" height="1004" alt="Image" src="https://github.com/user-attachments/assets/3a06e8ec-05f5-47b8-abd2-6a136e0c7881" />
