### ISSUE TITLE
IntelliJ 'New Project' - cannot select 'Linux' platform option

### ISSUE THREAD

**Issue by aromanelli** [flutter/flutter-intellij#5347]
## Steps to Reproduce

0) Make sure the flutter-intellij plugin is installed, using the 'dev' channel.
1) Start IntelliJ IDEA. Make sure it does *not* open directly into an existing project, but instead opens the "Welcome to IntelliJ IDEA" dialog. Close project if it opens directly to a project, which should return you to the welcome dialog.
2) Select the 'Projects' tab on the left side.
3) Select the 'New Project' button at the top. The 'New Project' dialog opens.
4) Select 'Flutter' on the left side.
5) Select the 'Next' button at the bottom. The next screen of the 'New Project' dialog will display.
6) The "Platforms:" section has a checkbox for 'Linux', but it is unchecked, and disabled, so that it is not checkable. I'm opening this issue assuming that it should be checkable.  Screenshot ...
![Screenshot from 2021-03-23 23-01-27](https://user-images.githubusercontent.com/409304/112263280-49d3d080-8c2c-11eb-88f4-e1b7df7c3a0a.png)

(When I mention "CLI" below I mean a terminal outside of the IDE.)

I was able to use the `flutter create counter` and `flutter run -d linux` commands via the CLI to create a Linux app and run it successfully.

I've tried restarting IntelliJ multiple times, and uninstalling/reinstalling the plugin multiple times, after confirming that Flutter was installed correctly (via snap) from the CLI previously, and that the SDKs paths were correct.

I've also did the `flutter config --enable-linux-desktop` on the CLI command successfully.

## Version info
Fedora 33 Workstation
Gnome 3.38.4
Wayland

IntelliJ IDEA 2020.3.3 (Community Edition)
Build #IC-203.7717.56, built on March 15, 2021
Runtime version: 11.0.10+8-b1145.96 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Flutter plugin version: 55.0.4-dev.3 flutter.dev (from repository: https://plugins.jetbrains.com/plugins/dev/list)

[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-12.1.pre at /home/adrian/snap/flutter/common/flutter
    • Framework revision 8264cb3e8a (13 days ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/adrian/Programming/Android/SDK
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

From 'flutter config' command via CLI ...
Settings:
  android-sdk: /home/adrian/Programming/Android/SDK
  enable-linux-desktop: true
  enable-windows-desktop: false
  android-studio-dir: /opt/android-studio

**Comment by stevemessick** [comment]
@aromanelli Is there any chance the Flutter SDK selected on page one of the new project wizard is different from the one you used on the command line? This problem *should* have been fixed in #5314, which is included in Flutter plugin 55.0.4-dev.3.

**Comment by aromanelli** [comment]
@stevemessick No. I only installed it once via snap.

I checked dnf before installing snap/flutter, and again just now.  The latest check ...
```
[adrian@ar-laptop-fedora ~]$ sudo dnf list flutter*
Last metadata expiration check: 0:00:16 ago on Wed 24 Mar 2021 03:52:32 PM PDT.
Error: No matching Packages to list
[adrian@ar-laptop-fedora ~]$ sudo dnf list dart*
Last metadata expiration check: 0:02:51 ago on Wed 24 Mar 2021 03:52:32 PM PDT.
Error: No matching Packages to list
[adrian@ar-laptop-fedora ~]$ 
```
Also tried doing a find on 'flutter' ...
```
[adrian@ar-laptop-fedora /]$ sudo find / -name flutter
[sudo] password for adrian: 
/home/adrian/.config/flutter
/home/adrian/.local/share/Trash/files/counter/cdounter/linux/flutter
/home/adrian/.local/share/Trash/files/counter/cdounter/android/app/src/main/java/io/flutter
/home/adrian/.local/share/Trash/files/counter/counter/linux/flutter
/home/adrian/.local/share/Trash/files/counter/counter/android/app/src/main/java/io/flutter
/home/adrian/.local/share/Trash/files/counter/counter/build/linux/x64/debug/CMakeFiles/counter.dir/flutter
/home/adrian/.local/share/Trash/files/counter/counter/build/linux/x64/debug/flutter
/home/adrian/snap/flutter
/home/adrian/snap/flutter/common/flutter
/home/adrian/snap/flutter/common/flutter/bin/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.1.0-nullsafety.2/example/windows/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/battery-1.0.11/android/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/battery-1.0.11/example/android/app/src/androidTest/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/battery-1.0.11/example/android/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.0-nullsafety.1/android/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.0-nullsafety.1/example/android/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity-3.0.0-nullsafety.1/android/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity-3.0.0-nullsafety.1/example/android/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/e2e-0.7.0+1/android/src/main/java/dev/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.0-nullsafety.1/android/src/test/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.0-nullsafety.1/android/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.0-nullsafety.1/example/linux/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.0-nullsafety.1/example/windows/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.0-nullsafety.1/example/android/app/src/androidTestDebug/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.0-nullsafety.1/example/android/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.1.0-nullsafety.3/example/linux/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-2.0.0-nullsafety.2/android/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-2.0.0-nullsafety.2/example/android/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.14/android/src/test/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.14/android/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.14/example/android/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.6.4+5/android/src/test/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.6.4+5/android/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.6.4+5/example/android/app/src/androidTestDebug/java/io/flutter
/home/adrian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.6.4+5/example/android/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/packages/flutter_tools/ide_templates/intellij/packages/flutter
/home/adrian/snap/flutter/common/flutter/packages/flutter_tools/templates/app/linux.tmpl/flutter
/home/adrian/snap/flutter/common/flutter/packages/flutter_tools/templates/app/windows.tmpl/flutter
/home/adrian/snap/flutter/common/flutter/packages/flutter
/home/adrian/snap/flutter/common/flutter/packages/integration_test/android/src/main/java/dev/flutter
/home/adrian/snap/flutter/common/flutter/dev/manual_tests/windows/flutter
/home/adrian/snap/flutter/common/flutter/dev/integration_tests/external_ui/android/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/dev/integration_tests/flutter_gallery/linux/flutter
/home/adrian/snap/flutter/common/flutter/dev/integration_tests/flutter_gallery/windows/flutter
/home/adrian/snap/flutter/common/flutter/dev/integration_tests/flutter_gallery/android/app/src/androidTest/java/io/flutter
/home/adrian/snap/flutter/common/flutter/dev/integration_tests/flutter_gallery/android/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/dev/integration_tests/android_module_host_with_custom_build_v2_embedding/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/dev/integration_tests/android_views/android/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/dev/integration_tests/android_host_app_v2_embedding/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/dev/integration_tests/android_custom_host_app/SampleApp/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/dev/integration_tests/module_host_with_custom_build_v2_embedding/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/dev/integration_tests/hybrid_android_views/android/app/src/main/java/io/flutter
/home/adrian/snap/flutter/common/flutter/dev/benchmarks/multiple_flutters/android/app/src/main/java/dev/flutter
/home/adrian/snap/flutter/common/flutter/examples/platform_view/android/app/src/main/java/io/flutter
find: ‘/run/user/1000/gvfs’: Permission denied
/var/lib/snapd/snap/bin/flutter
/var/lib/snapd/snap/flutter
/var/snap/flutter
[adrian@ar-laptop-fedora /]$ 
```
Also including a screenshot of my IntelliJ's settings panel. Note that there is no 'Flutter' entry under "Languages & Frameworks". Not sure if this is a problem or not?

![Screenshot from 2021-03-24 16-04-43](https://user-images.githubusercontent.com/409304/112394928-b7c6d900-8cba-11eb-92c6-a2baa6152bb7.png)

**Comment by aromanelli** [comment]
@stevemessick  I'd be glad to help out in any way, if you need me to do any debugging steps, investigation, etc.

**Comment by stevemessick** [comment]
@aromanelli Thanks for the offer. I'll take you up on that.

There is something wrong with your IntelliJ. I see you have both Dart and Flutter plugins installed yet neither is listed in the `Languages & Frameworks` section. I don't know how that can happen. They should both be there. Furthermore, your `flutter doctor -v` output includes Android Studio but not IntelliJ. 

What happens if you try to create a project using Android Studio 4.2 or Arctic Fox? There is no platform selection in 4.1.

What happens if you use the latest stable version of the Flutter plugin (not the dev channel)? This bug is fixed in version 54.1. (I mean, unless you've found a new bug.)

What happens if you use the stable channel of the Flutter SDK? You can [download](https://flutter.dev/docs/get-started/install/linux#install-flutter-manually) it to a temporary directory if you don't want to risk messing up your project.

If you still have time and nothing has worked, try installing IntelliJ from the [download page](https://www.jetbrains.com/idea/download/#section=linux) and use that.

You should expect to see both Dart and Flutter listed in the `Languages & Frameworks` section, and the `Linux` check box enabled in the new project wizard. If you get the first but not the second then you probably have found a new bug.

**Comment by aromanelli** [comment]
@stevemessick My IntelliJ was installed as a flatpak via the Fedora store, and not a manual download.

I went ahead and removed all plugins, uninstalled IntelliJ, uninstalled flutter/dart via snap, manually cleared out any and all configuration files in my home hierarchy, and ran both the dnf and flatpak uninstall unused commands. I did multiple reboots during all of that.

I then tried to reinstall flutter per [this page](https://flutter.dev/docs/get-started/install/linux) and it installed correctly (see output end of this comment).

However, trying to run ```flutter doctor``` for the first time failes on the 'pug get' because of a 502 bad gateway error, attempting multiple times. Going to pug.dartlang.org directly via my browser the I get a page that says the following ...
```
Error: Server Error
The server encountered a temporary error and could not complete your request.

Please try again in 30 seconds.
```
I'll try to continue tomorrow (assuming someone will fix the server problems in the morning), so I'll get back to you once I go through your checklist of things to try out.

```
[adrian@ar-laptop-fedora ~]$ sudo snap install flutter --classic
[sudo] password for adrian: 
flutter 0+git.e2e65ac from Flutter Team✓ installed
[adrian@ar-laptop-fedora ~]$ flutter sdk-path
Initializing Flutter
Downloading https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_2.0.3-stable.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  528M  100  528M    0     0  25.0M      0  0:00:21  0:00:21 --:--:-- 27.4M
Flutter initialized
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (6 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝


/home/adrian/snap/flutter/common/flutter
[adrian@ar-laptop-fedora ~]$ flutter doctor
502 Bad Gateway trying to find package node_preamble at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
502 Bad Gateway trying to find package node_preamble at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
502 Bad Gateway trying to find package node_preamble at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
502 Bad Gateway trying to find package node_preamble at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...
502 Bad Gateway trying to find package node_preamble at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...
502 Bad Gateway trying to find package node_preamble at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
502 Bad Gateway trying to find package node_preamble at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...
502 Bad Gateway trying to find package node_preamble at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 8 in 64 seconds...
502 Bad Gateway trying to find package node_preamble at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 9 in 64 seconds...
Running "flutter pub get" in flutter_tools...                          ⣻^C[adrian@ar-laptop-fedora ~]$ 
[adrian@ar-laptop-fedora ~]$ 
```

**Comment by stevemessick** [comment]
The https://pub.dev/ site was down for a while but is back now. (pub.dartlang.org redirects to pub.dev)

**Comment by aromanelli** [comment]
@stevemessick So I was able to complete the ```flutter doctor``` command, then install IntelliJ (flathub system) from the Fedora software app, then install the Flutter plugin from inside of IntelliJ (which also installed Dart, and then after that updated the Flutter plugin), and the problem still exists where either Flutter or Dart appears in the 'Languages & Frameworks' section of the IntelliJ settings.

Looking at the idea.log file it does show that the plugins were loaded ...

```
2021-03-25 13:30:14,495 [    781]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Dart (203.7759), Flutter (55.0.4-dev.3), Kotlin (203-1.4.31-release-IJ7148.5) 
```
There are though a few NoSuchFileException exceptions in the log (61-271), a IOException (326-352), and finally a Throwable assertion about doing work on the Swing UI thread (405-469). I'll attach the log file here for your review.

[idea.log](https://github.com/flutter/flutter-intellij/files/6207803/idea.log)

I'm going to try the non-flathub version of IntelliJ next, to see if that makes a difference, then on to your checklist after that.  But fundamentally, I would expect the plugin to be usable from the flathub version (everything being equal).

**Comment by aromanelli** [comment]
@stevemessick Tried using the downloaded version of IntelliJ (2020.3.3/#IC-203.7717.56), and just trying to install the default Flutter 54.1.4/Dart 203.7759 plugins (not the 'dev' ones), and neither plugin shows in the 'Languages & Frameworks' section. The kotlin plug does show (just to show that other plugins do get listed.

Attaching the idea.log file, has same kind of exceptions I mentioned earlier.

I'm going to stop here and get more input from you on what to try next, since the plugins are not showing up in either the flathub and/or downloaded versions of IntelliJ. Please advise.

[idea.log](https://github.com/flutter/flutter-intellij/files/6208035/idea.log)

**Comment by aromanelli** [comment]
@stevemessick I did discover that my original problem, that of the "Platforms" 'Linux' option has gone away with the downloaded version of IntelliJ and Fluuter plugin 54.1.4!

Using Flutter 55.0.4-dev.3 plugin also does not have the platform problem!

I switched back to the flatpak version, and the "Platform" 'Linux' option is again disabled.

The downloaded version still works fine.

**So, for my original ticket problem, its the flatpak version of IntelliJ that has the problem, not the downloaded one.**

**For the Flutter/Dart plugin not showing the settings menu, BOTH versions do not show it.**

**Comment by aromanelli** [comment]
Uploading the log file from the IntelliJ that works properly.

[idea.log](https://github.com/flutter/flutter-intellij/files/6208176/idea.log)

Comparing the working and not working log files, there's a descrepancy at the bottom of each log file ...

```
2021-03-25 15:17:10,831 [   1666]   INFO - penapi.wm.impl.GlobalMenuLinux - disable global-menu integration because some of shared libraries isn't installed: java.lang.UnsatisfiedLinkError: /opt/intellij/bin/libdbm64.so: libdbusmenu-glib.so.4: cannot open shared object file: No such file or directory 
2021-03-25 15:17:10,956 [   1791]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2021-03-25 15:17:10,958 [   1793]   INFO - ntellij.idea.ApplicationLoader - canDisableInputMethod spent 14 ms, found keyboard layouts: [(us, xkb), ], result==true 
2021-03-25 15:17:11,037 [   1872]   INFO - leBasedIndexDataInitialization - Initialization done: 628 
2021-03-25 15:17:11,060 [   1895]   INFO - exImpl$StubIndexInitialization - Initialization done: 23 
2021-03-25 15:17:15,782 [   6617]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: /opt/intellij/bin/fsnotifier64 
2021-03-25 15:17:15,793 [   6628]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2021-03-25 15:17:16,671 [   7506]   INFO - #io.flutter.sdk.FlutterCommand - /home/adrian/snap/flutter/common/flutter/bin/flutter [--no-color, config, --machine] 
2021-03-25 15:17:16,684 [   7519]   INFO -     #io.flutter.sdk.FlutterSdk - Calling flutter config --machine 
2021-03-25 15:17:17,283 [   8118]   INFO -     #io.flutter.sdk.FlutterSdk - flutter config --machine: 596ms 
2021-03-25 15:17:17,304 [   8139]   INFO -  #git4idea.commands.GitHandler - [.] git version 
2021-03-25 15:17:17,309 [   8144]   INFO -  #git4idea.commands.GitHandler - git version 2.30.2 
2021-03-25 15:17:17,317 [   8152]   INFO - ea.config.GitExecutableManager - Git version for /usr/bin/git: 2.30.2.0 (UNIX) 
```

```
2021-03-25 14:40:48,217 [   1653]   INFO - penapi.wm.impl.GlobalMenuLinux - disable global-menu integration because some of shared libraries isn't installed: java.lang.UnsatisfiedLinkError: /opt/intellij/bin/libdbm64.so: libdbusmenu-glib.so.4: cannot open shared object file: No such file or directory 
2021-03-25 14:40:48,341 [   1777]   INFO - ntellij.idea.ApplicationLoader - canDisableInputMethod spent 11 ms, found keyboard layouts: [(us, xkb), ], result==true 
2021-03-25 14:40:48,342 [   1778]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2021-03-25 14:40:48,629 [   2065]   INFO - leBasedIndexDataInitialization - Initialization done: 788 
2021-03-25 14:40:48,652 [   2088]   INFO - exImpl$StubIndexInitialization - Initialization done: 23 
2021-03-25 14:40:54,304 [   7740]   WARN - Container.ComponentManagerImpl - Do not use constructor injection (requestorClass=io.flutter.editor.ActiveEditorsOutlineService) 
2021-03-25 14:41:21,399 [  34835]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
2021-03-25 14:41:21,429 [  34865]   WARN - ConfigurableExtensionPointUtil - use other group instead of unexpected one: build.android
2021-03-25 14:41:21,822 [  35258]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: /opt/intellij/bin/fsnotifier64 
2021-03-25 14:41:21,831 [  35267]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2021-03-25 14:41:21,897 [  35333]   INFO - CompilerWorkspaceConfiguration - Available processors: 8 
2021-03-25 14:42:28,095 [ 101531]   INFO - rationStore.ComponentStoreImpl - Saving appDaemonCodeAnalyzerSettings took 13 ms, FileTypeManager took 11 ms 
```

**Comment by aromanelli** [comment]
@stevemessick Just a FYI, I'm planning on switching over from Fedora to Ubuntu this weekend tomorrow/Saturday, so if you want me to do any further testing before I do so (so that the environment is the same as when the bug was reported) let me know.

After the switch, I'll still be glad to help out in any way I can, assuming that the problem is purely a flatpak problem and not a Fedora 33/flatpak problem (and can be reproduced).

**Comment by stevemessick** [comment]
I'm glad the original issue has been resolved. Since the missing settings tabs involve both Dart and Flutter, I'm pretty sure it has nothing to do with the Flutter plugin. You'll need to check with JetBrains about that. @alexander-doroshko might be able to tell us if he's heard of this problem before. One thing did occur to me: If I read it correctly you install the Dart plugin as a consequence of installing the Flutter plugin. You might try installing Dart, *then* installing Flutter.

To resolve the IntelliJ distribution problem, you'll need to work with the Linux providers.

**Comment by aromanelli** [comment]
@stevemessick @alexander-doroshko I'll leave it up to you of course to close this issue or not, but I would add that you should be sure that the issue is not caused by the plugin coding doing path lookups and getting confused because flatpak installs to a different location (and diff rights?) than the native install does, so that the 'bug' is really with the plugin code and not IntelliJ proper. 

The plugin itself is not working right when IntelliJ is installed/ran through flatpak (you can't select the 'Linux' option in the plugin dialog), so that would make me thing that the "ball is still in your court", at least for diagnosing the problem to see if its a plugin vs flatpak vs IntelliJ issue. 

I would also respectively suggest that native and flatpak installs of IntelliJ should both be supported (in case they are not, for whatever reason), and if they are not, then explicitly state that in the README.md, to avoid future headaches.

Thanks for your time and efforts, they are appreciated by us all.

**Comment by stevemessick** [comment]
@aromanelli Good points. We're leaving this open for now. I need much better network bandwidth to do any experimentation, so I won't be doing anything until I can get back to the office.

Thanks for all the diagnostic info.

**Comment by alexander-doroshko** [comment]
> @alexander-doroshko might be able to tell us if he's heard of this problem before. 

I'm not aware of the problem. As far as I understand, flatpack distribution is not an official one, I mean it is supported not by JetBrains.

**Comment by stevemessick** [comment]
@aromanelli See also https://youtrack.jetbrains.com/issue/IDEA-189485

**Comment by aromanelli** [comment]
@stevemessick Wow, ok. That was a great read, TY for sharing the link.  Read through all of that, including the links inside of that link. Seems like things have been 'in progress' since 2018.

I had just assumed that flatpak would have the same current support as snap from the jetbrains guys in 2021, and that was my bad. Hopefully they give it full support, would be kind of awkward if the more proprietary snap system having better support that the flatpak one.

As I mentioned before, I'll just stick with the native installed version for now, until the dust clears.

Thanks for your efforts!

**Comment by aromanelli** [comment]
@stevemessick Remembered seeing some of [this issue](https://github.com/weisJ/auto-dark-mode/issues/20)'s errors in my logs; maybe this is related to the flatpak/plugin "Linux" disabled situation?

**Comment by stevemessick** [comment]
This isn't something the plugin can fix. It is due to the flatpak installation not including some Linux distro-specific libraries. See https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/issues/58
