### ISSUE TITLE
Horizontal tree indent guides is missing

### ISSUE THREAD

**Issue by talalong** [flutter/flutter-intellij#6253]
## Steps to Reproduce
I am using Intellij for my first Flutter demo app, but I am unable to see this tree indent guides (like the fig. 2)
Please help me how to enable this option. I've tried to check the option in _**Settings -> Languages & Frameworks -> Flutter -> Show UI Guides for build methods**_ . But it doesn't help.

<img width="462" alt="Screenshot 2022-07-01 at 13 23 52" src="https://user-images.githubusercontent.com/24271207/176885427-ed1ef318-3586-479f-be6f-a0614dfbb289.png">

This is what I want it to be:
<img width="342" alt="Screenshot 2022-07-01 at 13 24 44" src="https://user-images.githubusercontent.com/24271207/176885915-31e0436f-f300-4ceb-adcd-3fa0a2febd0a.png">

## Version info

[✓] Flutter (Channel stable, 3.0.3, on macOS 12.3.1 21E258 darwin-x64, locale en-GB)
    • Flutter version 3.0.3 at /Users/long.luong/Utils/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (9 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/long.luong/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/long.luong/Library/Android/sdk
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_331-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Users/long.luong/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Users/long.luong/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5787.30/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Users/long.luong/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5591.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 9B910A73-1944-49C8-9A2E-B540A0D1EE6F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by jukrb0x** [comment]
+1

**Comment by vladislav06** [comment]
same, but sometimes they will show in another project, sometimes not.

**Comment by stevemessick** [comment]
I can reproduce the problem and am investigating.

**Comment by stevemessick** [comment]
Something changed in Flutter 3 (or rather, Dart 2.17). The Dart analyzer is no longer producing a usable outline for the indent guides. The guides do work with Flutter 2.10.5 (Dart 2.16.2).

The question is, is this a bug in the Dart SDK, or did they have a breaking change that we need to adapt to?
@jacob314 @bwilkerson can either of you add anything useful?

**Comment by jukrb0x** [comment]
@stevemessick when i create new proj with flutter sdk either in terminal or android studio (i guess they are exactly the same), the new proj won't show the indent guides, but the projects downloaded from the internet works fine. (can't tell the versions now)

```
❯ flutter --version
Flutter 3.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cd41fdd495 (4 weeks ago) • 2022-06-08 09:52:13 -0700
Engine • revision f15f824b57
Tools • Dart 2.17.3 • DevTools 2.12.2
```

**Comment by stevemessick** [comment]
@jukrb0x If you open the old project and check the Flutter SDK in the Flutter preference page,  think you will find the old project is using a Flutter 2 SDK. The outline built by the Flutter 3 SDK is incorrect. Here are screen shots from the same project.

With Flutter 2:
<img width="449" alt="Screen Shot 2022-07-07 at 10 51 46 AM" src="https://user-images.githubusercontent.com/8518285/177840390-e79eafb2-7d3e-4bac-b737-c7e13efc86b1.png">

With Flutter 3:
<img width="354" alt="Screen Shot 2022-07-07 at 10 53 42 AM" src="https://user-images.githubusercontent.com/8518285/177840441-f8af2ced-4a19-4f40-8f1d-23411b5d263d.png">

I'm trying to get some help from the analyzer team.
https://github.com/dart-lang/sdk/issues/49421

**Comment by stevemessick** [comment]
@talalong @jukrb0x @vladislav06 Does your project show any Dart analysis errors?

As reported in the Dart issue linked above, this problem does not occur with the master channel of Flutter. If you are comfortable using master, then you might give it a try. I don't know when the next Flutter release will be, though.

**Comment by talalong** [comment]
@stevemessick There is no error on Dart analysis.
Switching to the master channel doesn't help as well.
<img width="713" alt="Screenshot 2022-07-08 at 11 42 21" src="https://user-images.githubusercontent.com/24271207/177965138-035b05e0-19dd-44ad-820b-7a0bbacab52a.png">

**Comment by stevemessick** [comment]
It seems nothing has changed in this part of the analyzer recently, and my issue is not reproducible by analysis server engineers. So, the Dart issue I linked earlier may be irrelevant.

@talalong I can't reproduce your problem with master. I was using a version with Dart "-262." then upgraded and got "-265." now. But my indent guides are fine with both. Can you attach some screen shots for us?

We'd like to see:
- The Flutter preferences page showing the version of Flutter used by the IDE, since it might be different from the command line.
- The Dart Analysis window, after pressing the red-arrow icon to restart it, and letting it finish.
- The Flutter Outline window with associated code.

Here are examples:
<img width="725" alt="Screen Shot 2022-07-08 at 10 57 46 AM" src="https://user-images.githubusercontent.com/8518285/178045666-f700ea4d-12c9-4997-9b0c-5475d22ff1d0.png">
<img width="367" alt="Screen Shot 2022-07-08 at 10 58 06 AM" src="https://user-images.githubusercontent.com/8518285/178045693-8bfb2be2-a0db-46ce-9557-4c2afa922342.png">
<img width="947" alt="Screen Shot 2022-07-08 at 11 02 35 AM" src="https://user-images.githubusercontent.com/8518285/178046315-160589b4-56f1-4e75-b5d6-b693886e5d1d.png">

**Comment by stevemessick** [comment]
@talalong Thanks for the update! Everything looks good. I'm puzzled why the indent guides do not show up. What other plugins have you installed, aside from Dart and Flutter?

**Comment by talalong** [comment]
@stevemessick I have many other plugins installed for the other projects in other languages. But having them disabled except Flutter, Dart and Kotlin (enabled by default) does not solve the my issue. I've tried to create a new project with master channel, but still the same issue.

**Comment by stevemessick** [comment]
@talalong Thanks, that was what I wanted to know about plugins. Could you enable verbose logging in the Flutter preferences page, then restart the IDE, let indexing and analysis finish, and attach the log file here? You can get the log file from `Help > Show Log in Finder`. Thanks!

**Comment by talalong** [comment]
@stevemessick here you go.
[idea.log](https://github.com/flutter/flutter-intellij/files/9074776/idea.log)

**Comment by stevemessick** [comment]
Thanks @talalong but there wasn't anything in the log. Do you have multiple Flutter projects? If so, do you want the settings to be different in them?

**Comment by talalong** [comment]
@stevemessick Do you mean there wasn't anything related to the issue or the file is empty? I can see a lot of warnings in the log.
I only have two Flutter projects but they are just simple demo applications. I want the settings to be the same for all Flutter projects.

**Comment by talalong** [comment]
@stevemessick I just found out one interesting point while creating a new project. If I choose Kotlin and Swift for Android and IOS, then the indent guide is showing.

<img width="343" alt="Screenshot 2022-07-12 at 12 33 25" src="https://user-images.githubusercontent.com/24271207/178478005-b9bfdb0a-85ae-4d44-acf2-39086fbfa6fc.png">

<img width="474" alt="Screenshot 2022-07-12 at 13 18 46" src="https://user-images.githubusercontent.com/24271207/178478211-f68fbc2a-a090-424a-b4bb-d5b1123ee90b.png">

**Comment by stevemessick** [comment]
> choose Kotlin and Swift

That's bizarre, but now I can reproduce the problem.

**Comment by stevemessick** [comment]
This is mostly for my own information, in case I get time to come back to this.

`WidgetIndentsHighlightingPassFactoryRegistrar.registerHighlightingPassFactory()` is called during project open processing, but way too early for us. The modules have not been created yet, so we can't know that the project has a Flutter module or not. If Kotlin is used in the Android module (I did not try iOS) the highlighting passes are re-created after the project has been fully initialized. And in that case the indent highlighter works.

**Comment by echogit** [comment]
Hi, has this issue being solved? I'm using the latest Flutter and VS Code and even with the settings item  "Editor > Guides: Indentation", the option "Controls whether the editor should render indent lines" is checked, 

![image](https://github.com/flutter/flutter-intellij/assets/4220801/ec2e1086-3d3e-4cad-9bf2-41749ce83120)
![image](https://github.com/flutter/flutter-intellij/assets/4220801/85c6eef3-65cb-4827-86d7-822517887b9e)

**Comment by parlough** [comment]
Hi @echogit, this is the repository for the Flutter IntelliJ plugin, so you may get better help on the https://github.com/Dart-Code/Dart-Code repository.

However, after a quick search, it looks like the DartCode plugin has experimental setting you can try to enable something similar in VS Code: https://dartcode.org/releases/v3-1/#preview-flutter-ui-guides

**Comment by Sukiet** [comment]
However, another my computer shares the same version of IDEA, dart and flutter plugin. But it's indent works well. Even if opening same project, the two computer performs differently.

**Comment by Sukiet** [comment]
Got solved by:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/6385173573522--Flutter-Dart-Horizontal-tree-indent-guides-is-missing

    1. Unchecking Show UI Guides for build methods 
    2. Apply
    3. Checking Show UI Guides for build methods on again
    4. Ok or Apply

**Comment by talalong** [comment]
The issue is too old. I am closing this.

**Comment by APdev93** [comment]
this is available on vscode too?

**Comment by anonfaded** [comment]
Still facing same issue on android studio while on vscode its working fine

**Comment by mahdimohammadi** [comment]
> Still facing same issue on android studio while on vscode its working fine

me too :):

**Comment by plyakin** [comment]
> По-прежнему сталкиваюсь с той же проблемой в Android Studio, в то время как в vscode всё работает нормально

Still not working(

**Comment by itumelengseema** [comment]
I'm downgrading to a old version of  IntelliJ Issue Still not fixed

**Comment by independentlearners** [comment]
Can a CLI based IDE like nvim do the samething?

**Comment by independentlearners** [comment]
I need help getting this sort of thing to work in nvim! Currently, it only works as shown in the first image, but the example in the second image doesn't work in nvim at the moment! Can anyone please help me with this in Neovim?
> 
> <img alt="Screenshot 2022-07-01 at 13 23 52" width="462" src="https://github.com/user-attachments/assets/602d7bcc-85b4-4c4d-8e2f-c2f398b778fd">
> <img alt="Screenshot 2022-07-01 at 13 24 44" width="342" src="https://user-images.githubusercontent.com/24271207/176885915-31e0436f-f300-4ceb-adcd-3fa0a2febd0a.png">
