### ISSUE TITLE
hot reload on save not work.

### ISSUE THREAD

**Issue by SilentlyYc** [flutter/flutter-intellij#6996]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

When I update the plugin to the latest (version 72.1.2), command+s hot reload no work.
There is no reaction after preservation.
When I go back to the version(version 72.0.2), It worked.
The hot reload configuration item is enabled.
I thought it was a plugin update that caused the configuration to be lost，but obviously not.
I don't know what happened.

## Version info

![image](https://github.com/flutter/flutter-intellij/assets/16175937/04b4cf6b-0329-4c5a-9ef8-bd5d5f25a527)

**Comment by lopo12123** [comment]
same problem

**Comment by whoevelmanns** [comment]
I have the same problem too.

**Comment by Haval-dev** [comment]
the same here.

**Comment by l619534951** [comment]
I upgraded the plugin to the latest version today and found that there was a problem, downgrade to **version 76.0.4** and it's working.

**Comment by nytoan** [comment]
Same problem.

**Comment by Lzyct** [comment]
any update about this issue?

**Comment by lukas-pierce** [comment]
same problem

**Comment by JaehyunYoo** [comment]
same problem.. please..

**Comment by zhoujia456888** [comment]
same problem

**Comment by IntCleastwood** [comment]
Same! Workaround 76.0.x worked for me

**Comment by HarryToo** [comment]
I tried updating to 76.2 today, but it seems the issue still exists.

**Comment by poorankharol** [comment]
Same problem

**Comment by SELiOTe** [comment]
Same, any update?

**Comment by jorgevvr** [comment]
Same problem on version 76.2.x

**Comment by jorgevvr** [comment]
> Same, any update?

To me for now i downgrade to version 76.0.x and is working fine.

**Comment by ByteSizedMarius** [comment]
dozens of people commenting "same" just makes it so no one can subscribe to this issue to get notified once it's fixed because of spam and literally helps no one. Everyone is aware this is an issue, just liking the original issue is more than enough. For now, just downgrade manually and do not update.

**Comment by SELiOTe** [comment]
Plugin bugs, but you can change one more dart file, and hot reload will working

**Comment by Sahilbhayani** [comment]
For now downgrad flutter plugin manually..

Downloading the 76.0.x or earlier zip file from this link
https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable

And install the plugin manually from file, which will make the hot reload works again

![Screenshot from 2023-11-06 18-34-10](https://github.com/flutter/flutter-intellij/assets/77524691/e237369e-2f40-42cf-b20d-b10d0a31165b)
![Screenshot from 2023-11-06 18-34-10](https://github.com/flutter/flutter-intellij/assets/77524691/1ab627a8-9886-476d-84ce-22c48c15f477)

**Comment by jwren** [comment]
Hi all, I believe that this issue is fixed with the point release of 76.3.x that I just pushed out.  Please let me know otherwise.

Thank you for the various reports and comments above.

**Comment by jwren** [comment]
(not yet showing up on the server, give it a few minutes)

**Comment by l619534951** [comment]
It has been fixed on my computer.

flutter plugin: 76.3.4
IntelliJ IDEA 2023.2.4 (Ultimate Edition)
Build #IU-232.10203.10, built on October 25, 2023

**Comment by jorgevvr** [comment]
Fixed for me too.
flutter plugin: 76.3.4

**Comment by jwren** [comment]
Thank you for confirming.  Closing this issue out.  If there is still a regression for some platform version, open a new issue and tag me to escalate.

**Comment by Gaweringo** [comment]
I am having the same issue, that it's not hot reloading on save (format on save works), on `Android Studio Hedgehog | 2023.1.1 Patch 2` with the Flutter plugin `78.0.1` and Flutter version:
```
Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bae5e49bc2 (6 days ago) • 2024-02-13 17:46:18 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1
```

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.19045.4046], locale en-AT)
    ! Warning: `flutter` on your path resolves to C:\Users\gawer\scoop\apps\flutter\3.19.0\bin\flutter, which is not
      inside your current Flutter SDK checkout at C:\Users\gawer\scoop\apps\flutter\current. Consider adding
      C:\Users\gawer\scoop\apps\flutter\current\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\gawer\scoop\apps\flutter\3.19.0\bin\dart, which is not inside
      your current Flutter SDK checkout at C:\Users\gawer\scoop\apps\flutter\current. Consider adding
      C:\Users\gawer\scoop\apps\flutter\current\bin to the front of your path.
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.0)
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
[✓] VS Code (version 1.86.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category
```
It works in VS Code with the same project.

**Comment by theRookieCoder** [comment]
I still have this issue on the latest plug in version `78.1.1`, in fact I'm not even able to use the `Ctrl+\` shortcut to trigger hot reload, only the button in the run console works. Somehow `Shift+Ctrl+\` works for hot restarting.

```
Flutter 3.19.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7482962148 (8 days ago) • 2024-02-27 16:51:22 -0500
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1
```
```
[✓] Flutter (Channel stable, 3.19.2, on Fedora Linux 39 (KDE Plasma) 6.7.6-200.fc39.x86_64)
    • Flutter version 3.19.2 on channel stable at /home/<user>/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (8 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/<user>/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /home/<user>/Android/Sdk
    • Java binary at: /home/<user>/.local/share/JetBrains/Toolbox/apps/android-studio-2/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.17-11446219)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6 (Fedora 17.0.6-2.fc39)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.9.5

[✓] Android Studio (version 2023.3)
    • Android Studio at /home/<user>/.local/share/JetBrains/Toolbox/apps/android-studio-2
    • Flutter plugin version 78.1.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.17-11446219)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at /home/<user>/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.87.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.85.20240301

[✓] Network resources
    • All expected network resources are available.
```
